# TODO:
#   - caching intermediate image builds
---
trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build/validate images
  jobs:
    - template: ado-templates/docker-build.yml
      parameters:
        name: Transcriber
        imageName: 'binhrobles/transcribe-transcriber'
        dockerfile: '$(Build.SourcesDirectory)/transcriber/Dockerfile'

    - template: ado-templates/docker-build.yml
      parameters:
        name: NGINX
        imageName: 'binhrobles/transcribe-nginx'
        dockerfile: '$(Build.SourcesDirectory)/nginx/Dockerfile'

- stage: PublishPersonal
  displayName: Deploy to personal account
  variables:
    - group: personal-aws-info   # imports pulumi.access.token, aws creds, accountId for personal aws account
  jobs:
    - template: ado-templates/services-deploy.yml
      parameters:
        environment: personal

    - template: pipeline-templates/client-deploy.template.yml
      parameters:
        environment: personal
        artifactName: 'personal-$(Build.SourceVersion)' # append the git hash to the artifact name
