# TODO:
#   - infra deploy
#   - separate docker build/push template
#   - caching intermediate image builds
---
trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: Transcriber
    displayName: Build Transcriber
    variables:
      imageName: 'binhrobles/transcriber-transcribe'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: $(imageName)
        command: build
        dockerfile: '$(Build.SourcesDirectory)/transcriber/Dockerfile'

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: DockerHub
        repository: '$(imageName)'
        command: 'push'
        tags: '$(Build.BuildId)'
