# TODO:
#   - infra deploy
#   - separate docker build/push template
#   - caching intermediate image builds
---
trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build images
  jobs:
    - job: Transcriber
      displayName: Build Transcriber
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - template: ado-templates/docker-build.yml
        parameters:
          pImageName: 'binhrobles/transcribe-transcriber'
          pDockerfile: '$(Build.SourcesDirectory)/transcriber/Dockerfile'

    - job: NGINX
      displayName: Build NGINX
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - template: ado-templates/docker-build.yml
        parameters:
          pImageName: 'binhrobles/transcribe-nginx'
          pDockerfile: '$(Build.SourcesDirectory)/nginx/Dockerfile'
