# TODO:
#   - infra deploy
#   - separate docker build/push template
#   - caching intermediate image builds
---
trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build/validate images
  jobs:
    - template: ado-templates/docker-build.yml
      parameters:
        name: Transcriber
        imageName: 'binhrobles/transcribe-transcriber'
        dockerfile: '$(Build.SourcesDirectory)/transcriber/Dockerfile'

    - template: ado-templates/docker-build.yml
      parameters:
        name: NGINX
        imageName: 'binhrobles/transcribe-nginx'
        dockerfile: '$(Build.SourcesDirectory)/nginx/Dockerfile'

- stage: PublishPersonal
  displayName: Deploy to personal account
  jobs:
    - template: ado-templates/infra-deploy.yml
      parameters:
        environment: personal
