---
parameters:
- name: name
  type: string
- name: imageName
  type: string
- name: dockerfile
  type: string

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        containerRegistry: DockerHub
        repository: ${{ parameters.imageName }}
        dockerfile: ${{ parameters.dockerfile }}
        tags: |
          $(Build.SourceVersion)
          latest
