---
parameters:
- name: environment
  type: string

jobs:
  - job: Infrastructure
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Cache@2
        displayName: Cache Yarn packages
        inputs:
          key: 'pulumi | yarn | "$(Agent.OS)" | yarn.lock'
          path: $(YARN_CACHE_FOLDER)

      - script: yarn
        displayName: 'install pulumi dependencies'
        workingDirectory: 'infra/'

        # runs `pulumi preview` if PR or manual build invoked
      - task: Pulumi@1
        condition: or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.Reason'], 'Manual'))
        inputs:
          command: 'preview'
          cwd: 'infra/'
          stack: 'binhrobles/transcribe-backend/${{ parameters.environment }}'

        # runs `pulumi up --yes` if triggered by Git push
      - task: Pulumi@1
        condition: or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'))
        inputs:
          command: 'up'
          cwd: 'infra/'
          stack: 'binhrobles/transcribe-backend/${{ parameters.environment }}'
          args: '--yes'

      - script: |
          echo "##vso[task.setvariable variable=transcribeEndpoint;isOutput=true]$(pulumi stack output endpoint)"
        displayName: 'Set stack outputs as variables'
        workingDirectory: 'infra/'
        name: 'pulumi'
